export const urlList = {
  list1: [
    'https://www.ouyi.cc/markets/swap-info/BTC-usdt',
    'https://www.ouyi.cc/markets/swap-info/ETH-usdt',
    'https://www.ouyi.cc/markets/swap-info/LTC-usdt',
    'https://www.ouyi.cc/markets/swap-info/DOT-usdt',
    'https://www.ouyi.cc/markets/swap-info/DOGE-usdt',
    'https://www.ouyi.cc/markets/swap-info/XRP-usdt',
    'https://www.ouyi.cc/markets/swap-info/ETC-usdt',
    'https://www.ouyi.cc/markets/swap-info/EOS-usdt',
    'https://www.ouyi.cc/markets/swap-info/MATIC-usdt',
    'https://www.ouyi.cc/markets/swap-info/BZZ-usdt',
    'https://www.ouyi.cc/markets/swap-info/1INCH-usdt',
    'https://www.ouyi.cc/markets/swap-info/AAVE-usdt',
    'https://www.ouyi.cc/markets/swap-info/ADA-usdt',
    'https://www.ouyi.cc/markets/swap-info/ALPHA-usdt',
    'https://www.ouyi.cc/markets/swap-info/ALGO-usdt',
    'https://www.ouyi.cc/markets/swap-info/ANC-usdt',
    'https://www.ouyi.cc/markets/swap-info/ANT-usdt',
    'https://www.ouyi.cc/markets/swap-info/ATOM-usdt',
    'https://www.ouyi.cc/markets/swap-info/AVAX-usdt',
    'https://www.ouyi.cc/markets/swap-info/BADGER-usdt'

  ],

  list2: [
    'https://www.ouyi.cc/markets/swap-info/BAL-usdt',
    'https://www.ouyi.cc/markets/swap-info/BAND-usdt',
    'https://www.ouyi.cc/markets/swap-info/BAT-usdt',
    'https://www.ouyi.cc/markets/swap-info/BCH-usdt',
    'https://www.ouyi.cc/markets/swap-info/BNT-usdt',
    'https://www.ouyi.cc/markets/swap-info/BTM-usdt',
    'https://www.ouyi.cc/markets/swap-info/BSV-usdt',
    'https://www.ouyi.cc/markets/swap-info/BTT-usdt',
    'https://www.ouyi.cc/markets/swap-info/CFX-usdt',
    'https://www.ouyi.cc/markets/swap-info/CHZ-usdt',
    'https://www.ouyi.cc/markets/swap-info/COMP-usdt',
    'https://www.ouyi.cc/markets/swap-info/CONV-usdt',
    'https://www.ouyi.cc/markets/swap-info/CRO-usdt',
    'https://www.ouyi.cc/markets/swap-info/CSPR-usdt',
    'https://www.ouyi.cc/markets/swap-info/CRV-usdt',
    'https://www.ouyi.cc/markets/swap-info/CVC-usdt',
    'https://www.ouyi.cc/markets/swap-info/DASH-usdt',
    'https://www.ouyi.cc/markets/swap-info/DORA-usdt',
    'https://www.ouyi.cc/markets/swap-info/EGLD-usdt',
    'https://www.ouyi.cc/markets/swap-info/ENJ-usdt'

  ],

  list3: [
    'https://www.ouyi.cc/markets/swap-info/FTM-usdt',
    'https://www.ouyi.cc/markets/swap-info/FIL-usdt',
    'https://www.ouyi.cc/markets/swap-info/FLM-usdt',
    'https://www.ouyi.cc/markets/swap-info/GRT-usdt',
    'https://www.ouyi.cc/markets/swap-info/IOST-usdt',
    'https://www.ouyi.cc/markets/swap-info/ICP-usdt',
    'https://www.ouyi.cc/markets/swap-info/IOTA-usdt',
    'https://www.ouyi.cc/markets/swap-info/JST-usdt',
    'https://www.ouyi.cc/markets/swap-info/KNC-usdt',
    'https://www.ouyi.cc/markets/swap-info/KSM-usdt',
    'https://www.ouyi.cc/markets/swap-info/LON-usdt',
    'https://www.ouyi.cc/markets/swap-info/LINK-usdt',
    'https://www.ouyi.cc/markets/swap-info/LPT-usdt',
    'https://www.ouyi.cc/markets/swap-info/LAT-usdt',
    'https://www.ouyi.cc/markets/swap-info/LUNA-usdt',
    'https://www.ouyi.cc/markets/swap-info/LRC-usdt',
    'https://www.ouyi.cc/markets/swap-info/MASK-usdt',
    'https://www.ouyi.cc/markets/swap-info/MANA-usdt',
    'https://www.ouyi.cc/markets/swap-info/MIR-usdt',
    'https://www.ouyi.cc/markets/swap-info/MINA-usdt'
  ],

  list4: [
    'https://www.ouyi.cc/markets/swap-info/NEAR-usdt',
    'https://www.ouyi.cc/markets/swap-info/MKR-usdt',
    'https://www.ouyi.cc/markets/swap-info/NEO-usdt',
    'https://www.ouyi.cc/markets/swap-info/OMG-usdt',
    'https://www.ouyi.cc/markets/swap-info/ONT-usdt',
    'https://www.ouyi.cc/markets/swap-info/PERP-usdt',
    'https://www.ouyi.cc/markets/swap-info/QTUM-usdt',
    'https://www.ouyi.cc/markets/swap-info/RVN-usdt',
    'https://www.ouyi.cc/markets/swap-info/REN-usdt',
    'https://www.ouyi.cc/markets/swap-info/RSR-usdt',
    'https://www.ouyi.cc/markets/swap-info/SOL-usdt',
    'https://www.ouyi.cc/markets/swap-info/SRM-usdt',
    'https://www.ouyi.cc/markets/swap-info/SAND-usdt',
    'https://www.ouyi.cc/markets/swap-info/SC-usdt',
    'https://www.ouyi.cc/markets/swap-info/STORJ-usdt',
    'https://www.ouyi.cc/markets/swap-info/SNX-usdt',
    'https://www.ouyi.cc/markets/swap-info/SHIB-usdt',
    'https://www.ouyi.cc/markets/swap-info/SUSHI-usdt',
    'https://www.ouyi.cc/markets/swap-info/SWRV-usdt',
    'https://www.ouyi.cc/markets/swap-info/THETA-usdt',
    'https://www.ouyi.cc/markets/swap-info/TORN-usdt'
  ],

  list5: [
    'https://www.ouyi.cc/markets/swap-info/TRB-usdt',
    'https://www.ouyi.cc/markets/swap-info/TRX-usdt',
    'https://www.ouyi.cc/markets/swap-info/UMA-usdt',
    'https://www.ouyi.cc/markets/swap-info/UNI-usdt',
    'https://www.ouyi.cc/markets/swap-info/WAVES-usdt',
    'https://www.ouyi.cc/markets/swap-info/WNXM-usdt',
    'https://www.ouyi.cc/markets/swap-info/XLM-usdt',
    'https://www.ouyi.cc/markets/swap-info/XCH-usdt',
    'https://www.ouyi.cc/markets/swap-info/XMR-usdt',
    'https://www.ouyi.cc/markets/swap-info/XEM-usdt',
    'https://www.ouyi.cc/markets/swap-info/XTZ-usdt',
    'https://www.ouyi.cc/markets/swap-info/YFI-usdt',
    'https://www.ouyi.cc/markets/swap-info/YFII-usdt',
    'https://www.ouyi.cc/markets/swap-info/ZEC-usdt',
    'https://www.ouyi.cc/markets/swap-info/ZEN-usdt',
    'https://www.ouyi.cc/markets/swap-info/ZIL-usdt',
    'https://www.ouyi.cc/markets/swap-info/ZRX-usdt'
  ]
}
